// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Firebase options for the Pamphlet project (courses, topics, questions).
class PamphletFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'PamphletFirebaseOptions have not been configured for web.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.linux:
        return android; // Use Android config for Linux desktop development
      default:
        throw UnsupportedError(
          'PamphletFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABwmdF87dOyo3cdRu0bWSVV-aUTUPXDJo',
    appId: '1:612520926911:android:fb6eafd60bddcb4c53b00a',
    messagingSenderId: '612520926911',
    projectId: 'pamphlet-471f2',
    storageBucket: 'pamphlet-471f2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABwmdF87dOyo3cdRu0bWSVV-aUTUPXDJo',
    appId:
        '1:612520926911:ios:fb6eafd60bddcb4c53b00a', // Update if you have iOS config
    messagingSenderId: '612520926911',
    projectId: 'pamphlet-471f2',
    storageBucket: 'pamphlet-471f2.firebasestorage.app',
    iosBundleId: 'com.ronzodev.solveit',
  );
}

/// Firebase options for the ECZ project (grades, subjects, past papers).
class EczFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'EczFirebaseOptions have not been configured for web.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.linux:
        return android; // Use Android config for Linux desktop development
      default:
        throw UnsupportedError(
          'EczFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZWmjmVBye15hXSMVKHipS90cuUzLTlGw',
    appId: '1:568458543301:android:fbf70addfcbde0d136f0ac',
    messagingSenderId: '568458543301',
    projectId: 'ecz-project',
    storageBucket: 'ecz-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-6-6RjUyKGelHtN9Jz7gYeaK6Gzow3hY',
    appId: '1:568458543301:ios:0608941eda9fe88136f0ac',
    messagingSenderId: '568458543301',
    projectId: 'ecz-project',
    storageBucket: 'ecz-project.appspot.com',
    iosBundleId: 'com.ronzodev.solveit',
  );
}

/// Default [FirebaseOptions] - using Pamphlet as default for the app.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform =>
      PamphletFirebaseOptions.currentPlatform;
}
